name: Deploy Microservices

on:
  push: 
    branches:
      - master

  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      ARM_SUBSCRIPTION_ID: "1c0c4b42-8d2c-4f69-ad33-44a89af6f08e"
      ARM_CLIENT_ID: "a65b22b8-2d1e-4315-8b91-5c0fbe51c39d"
      ARM_TENANT_ID: "2625129d-99a2-4df5-988e-5c5d07e7d0fb"
      CONTAINER_REGISTRY: "distinctionweek9.azurecr.io"
      AKS_RESOURCE_GROUP: "deakinuni"
      AKS_CLUSTER_NAME: "distinctionweek9"

    steps:
      
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./scripts/terraform

      - name: Import existing Container Registry
        working-directory: ./scripts/terraform
        run: |
          terraform import azurerm_container_registry.distinctionweek9 /subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/deakinuni/providers/Microsoft.ContainerRegistry/registries/distinctionweek9
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve \
            -var "ARM_CLIENT_ID=${{ env.ARM_CLIENT_ID }}" \
            -var "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var "ARM_TENANT_ID=${{ env.ARM_TENANT_ID }}" \
            -var "ARM_SUBSCRIPTION_ID=${{ env.ARM_SUBSCRIPTION_ID }}" \
            -var "CONTAINER_REGISTRY=${{ env.CONTAINER_REGISTRY }}" \
            -var "REGISTRY_UN=${{ secrets.REGISTRY_UN }}" \
            -var "REGISTRY_PW=${{ secrets.REGISTRY_PW }}"
        working-directory: ./scripts/terraform

      - name: Install Kubectl
        run: |
          az aks install-cli
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

      - name: Build
        run: ./scripts/build-image.sh

      - name: Publish
        run: ./scripts/push-image.sh

      - name: Deploy
        run: ./scripts/deploy.sh
