name: Deploy Microservices

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure
        run: |
          echo "${{ secrets.ARM_CLIENT_SECRET }}" | az login --service-principal -u "${{ secrets.ARM_CLIENT_ID }}" --tenant "${{ secrets.ARM_TENANT_ID }}" 
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.CONTAINER_REGISTRY }}

      - name: Build and push book_catalog Docker image
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/book_catalog:latest -f ./book_catalog/Dockerfile ./book_catalog
          docker push ${{ secrets.CONTAINER_REGISTRY }}/book_catalog:latest

      - name: Build and push inventory_management Docker image
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/inventory_management:latest -f ./inventory_management/Dockerfile ./inventory_management
          docker push ${{ secrets.CONTAINER_REGISTRY }}/inventory_management:latest

  terraform:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Install kubectl
        run: |
          az aks install-cli

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group deakinuni --name distinctionweek9

      - name: Deploy book_catalog to AKS
        run: |
          kubectl apply -f ./kubernetes/book_catalog/deployment.yaml
          kubectl apply -f ./kubernetes/book_catalog/service.yaml

      - name: Deploy inventory_management to AKS
        run: |
          kubectl apply -f ./kubernetes/inventory_management/deployment.yaml
          kubectl apply -f ./kubernetes/inventory_management/service.yaml
