name: Deploy Microservices

on:
  push:
    branches:
      - master
# Add the id-token permission
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Images
      run: |
        docker build -t ${{ secrets.REGISTRYZ_UN }}.azurecr.io/book-catalog:latest ./book_catalog
        docker build -t ${{ secrets.REGISTRYZ_UN }}.azurecr.io/inventory-management:latest ./inventory_management
        echo ${{ secrets.REGISTRY_PW }} | docker login ${{ secrets.REGISTRY_UN }}.azurecr.io --username ${{ secrets.REGISTRY_UN }} --password-stdin
        docker push ${{ secrets.REGISTRY_UN }}.azurecr.io/book-catalog:latest
        docker push ${{ secrets.REGISTRY_UN }}.azurecr.io/inventory-management:latest

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/book_catalog-deployment.yaml
        kubectl apply -f k8s/inventory_management-deployment.yaml
